image:
  file: .gitpod.Dockerfile
tasks:
  - init: npm install
    command: echo init
  - command: export TZ="Asia/Tokyo"
    command: export URL=`gp url 8080`
    command: echo command
    command: eval $(gp env -e) && npm run build
    command: npm run start
